server:
  port: ${PORT: 8080}

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  application:
    name: ecomerce
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob.non_contextual_creation: true

jwt:
  secret: ${JWT_SECRET}
  accessExpiration: ${JWT_ACCESS_EXPIRATION:86400000}
  refreshExpiration: ${JWT_REFRESH_EXPIRATION:604800000}
cloudinary:
  cloudName: ${CLOUD_NAME}
  apiKey: ${API_KEY}
  apiSecret: ${API_SECRET}
momo:
  partnerCode: ${PARTNER_CODE}
  accessKey: ${ACCESS_KEY}
  secretKey: ${SECRET_KEY}
  endpoint: ${END_POINT}
  redirectUrl: ${REDIRECT_URL}
  ipnUrl: ${IPN_URL}